version: '3'

services:
  backend:
    env_file:
        "./backend/env-backend"
    ports:
      - "3001:8080"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    volumes:
      - ./data-public:/usr/app/public

  frontend:
    env_file:
        "./frontend/env-frontend"
    ports:
      - "3000:3000"
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
